### ISSUE TITLE
arm64 asm syntax highlighting should support coloring hexidecimal & binary constants

### ISSUE THREAD

**Issue by iankronquist** [compnerd/arm64asm-vim#1]
This syntax highlighting file uses the following regexes to match numeric constants. Unfortunately, this doesn't highlight hexidecimal constants like in the instruction `cmp x3, #0x1000`, or binary constants like `mov x2, #0b11101`.
```
syntax match AArch64Number /#-\?\d\+/
syntax match AArch64Number /#([^)]\+)/
```

Adding the following lines seems to do the trick
```
syntax match AArch64Number /#\?-\?0x\x\+/
syntax match AArch64Number /#\?-\?0b[01]\+/
```
Additionally, we should consider marking the leading `#` optional with `\?` as it's not required by all assemblers.

**Comment by compnerd** [comment]
Interesting, do you happen to know which assemblers do not require the prefix?  IIRC, I had based the syntax on a cursory glance at the ARM ARM.

**Comment by iankronquist** [comment]
binutils' gas seems to accept immediates with and without the `#`.

**Comment by compnerd** [comment]
@iankronquist ah, thanks!
